language: python

python:
    - "3.6"

services: 
    - postgresql
    
before_script:
    - psql -c 'create database snippets;' -U postgres
    - python manage.py makemigrations
    - python manage.py migrate
    
install:
    - pip install -r requirements.txt

script:
    - coverage run --source='snippets' manage.py test

after_success:
    - coveralls