language: python

python:
  - "3.6"

addon:
  - postgresql: "9.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before script:
  - psql -c "create database django_auth;" -U postgres

script:
  - coverage run --omit="*wsgi*,*base*,*staging*,*production*," --source="snippets" manage.py test snippets --verbosity 3
  - coverage report -m
  - coveralls
after script:
  - coveralls